// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmavoxaecahhlerlbpne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtYXZveGFlY2FoaGxlcmxicG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTkzMTEsImV4cCI6MjA3MTk3NTMxMX0.xnjvamfTt5iBZsdYBZqq63KLf8hAxNOqf9L3FdtIck8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});